### ISSUE TITLE
where to attach the marker?

### ISSUE THREAD

**Issue by Toytiny** [Chen3110/mmBody#1]
Great work! We are also interested in generating human body mesh using Mosh++ with SMPL model.  We saw in your paper that 37 markers are attached near human joints. Could you give us a layout of these markers? To generate the standard human mesh,  do we need to follow the same marker layout or just use a random one?

**Comment by Chen3110** [comment]
Thank you for your interest! The layout of markers is shown in the picture as follows. You don't need to follow the rigid layout as you can adjust the layout in the config file of Mosh++.
![image](https://github.com/Chen3110/mmBody/assets/53890856/fed8624b-4f43-4caf-ba3f-8e72928be7ac)
